// ── Local Ollama client (browser → user's machine) ─────────────────────────────
// The "explain why this file was flagged" summary is generated by an Ollama
// instance running on the viewer's machine. It is called directly from the
// browser, so Ollama must allow the origin: `OLLAMA_ORIGINS=* ollama serve`.

import { categoryLabel } from "./gdpr";
import type { Finding, ScannedFile } from "./types";

export const OLLAMA_URL = (process.env.NEXT_PUBLIC_OLLAMA_URL ?? "http://localhost:11434").replace(
  /\/$/,
  ""
);
export const OLLAMA_MODEL = process.env.NEXT_PUBLIC_OLLAMA_MODEL ?? "llama3.2";

function buildPrompt(file: ScannedFile): string {
  const found = file.findings
    .map((f) => `- ${categoryLabel(f.category)} (${Math.round(f.confidence * 100)}% confidence): "${f.snippet}"`)
    .join("\n");
  const excerpt = file.text.slice(0, 1200);
  return [
    "You are a GDPR compliance assistant for an internal data-discovery tool.",
    "In 2–3 short, plain-English sentences, explain to the file's owner WHY this",
    "file was flagged as containing personal data, and what GDPR risk it poses.",
    "Be concise and non-alarming. Do not repeat the raw values; refer to the data types.",
    "",
    `File name: ${file.name}`,
    `Source: ${file.sourceType}`,
    "",
    "Detected personal data:",
    found,
    "",
    "File excerpt:",
    `"""${excerpt}"""`,
    "",
    "Explanation:",
  ].join("\n");
}

/** Reachability probe with a short timeout. */
export async function ollamaAvailable(timeoutMs = 1500): Promise<boolean> {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), timeoutMs);
    const res = await fetch(`${OLLAMA_URL}/api/tags`, { signal: ctrl.signal });
    clearTimeout(t);
    return res.ok;
  } catch {
    return false;
  }
}

export interface SummaryResult {
  text: string;
  source: "ollama" | "fallback";
  model?: string;
}

/** Streamed generation. Calls onToken for each chunk; resolves with full text. */
export async function streamSummary(
  file: ScannedFile,
  onToken: (chunk: string) => void,
  opts: { model?: string; signal?: AbortSignal } = {}
): Promise<SummaryResult> {
  const model = opts.model ?? OLLAMA_MODEL;
  const res = await fetch(`${OLLAMA_URL}/api/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ model, prompt: buildPrompt(file), stream: true }),
    signal: opts.signal,
  });
  if (!res.ok || !res.body) throw new Error(`Ollama responded ${res.status}`);

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let full = "";
  let buffer = "";
  // Ollama streams newline-delimited JSON objects: {"response":"...","done":false}
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        const obj = JSON.parse(trimmed);
        if (obj.response) {
          full += obj.response;
          onToken(obj.response);
        }
      } catch {
        /* partial line — ignore */
      }
    }
  }
  return { text: full.trim(), source: "ollama", model };
}

/** Deterministic, no-LLM summary used when Ollama is unreachable. */
export function fallbackSummary(file: ScannedFile, findings: Finding[]): string {
  const types = Array.from(new Set(findings.map((f) => categoryLabel(f.category))));
  const list =
    types.length === 1
      ? types[0].toLowerCase()
      : `${types.slice(0, -1).map((t) => t.toLowerCase()).join(", ")} and ${types[types.length - 1].toLowerCase()}`;
  const articles = Array.from(new Set(findings.flatMap((f) => f.gdprArticles))).sort();
  return (
    `“${file.name}” was flagged because the scanner detected ${findings.length} item${findings.length === 1 ? "" : "s"} of personal data — ${list}. ` +
    `Under GDPR this kind of data must be minimised and erased once it is no longer needed (${articles.join(", ")}). ` +
    `Review each finding below and decide whether the file is still required for business, or should be cleaned up.`
  );
}
